### ISSUE TITLE
为什么我用华为可以保存到相册 用oppo就不行

### ISSUE THREAD

**Issue by wjy397** [lisen87/image_pickers#49]
为什么我用华为可以保存到相册 用oppo就不行

**Comment by lisen87** [comment]
是不是没有找到？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lisen87/image_pickers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 上午9:48
收件人:&nbsp;"lisen87/image_pickers"<image_pickers@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[lisen87/image_pickers] 为什么我用华为可以保存到相册 用oppo就不行 (#49)





 
为什么我用华为可以保存到相册 用oppo就不行

**Comment by wjy397** [comment]
> 是不是没有找到？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lisen87/image_pickers" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月25日(星期五) 上午9:48 收件人:&nbsp;"lisen87/image_pickers"<image_pickers@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[lisen87/image_pickers] 为什么我用华为可以保存到相册 用oppo就不行 (#49) 为什么我用华为可以保存到相册 用oppo就不行 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问没有找到是什么意思？  我尝试了很多次 确认是相册里没有  但是华为手机可以  是我哪里操作有问题吗  ？   并且我打包的时候一直报错 Could not resolve com.github.LuckSiege.PictureSelector:picture_library:v2.4.2.
请问 又是什么情况

**Comment by wjy397** [comment]
> > 是不是没有找到？
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "lisen87/image_pickers" <[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年9月25日(星期五) 上午9:48 收件人: "lisen87/image_pickers"<[image_pickers@noreply.github.com](mailto:image_pickers@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: [lisen87/image_pickers] 为什么我用华为可以保存到相册 用oppo就不行 (#49) 为什么我用华为可以保存到相册 用oppo就不行 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 请问没有找到是什么意思？ 我尝试了很多次 确认是相册里没有 但是华为手机可以 是我哪里操作有问题吗 ？ 并且我打包的时候一直报错 Could not resolve com.github.LuckSiege.PictureSelector:picture_library:v2.4.2.
> 请问 又是什么情况

  _saveScreen() async {
    try {
      RenderRepaintBoundary boundary =
          repainKey.currentContext.findRenderObject();
      ui.Image image = await boundary.toImage();
      ByteData byteData =
          await image.toByteData(format: ui.ImageByteFormat.png);
      //这个对象就是图片数据
      Uint8List pngBytes = byteData.buffer.asUint8List();

      String path = await ImagePickers.saveByteDataImageToGallery(pngBytes);
      File(path);
      ToastUtil.showSuccess('保存成功,请查看相册');
    } catch (e) {
      ToastUtil.showError('保存失败!');
    }
  }

这是我的代码

**Comment by lisen87** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lisen87/image_pickers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 上午9:56
收件人:&nbsp;"lisen87/image_pickers"<image_pickers@noreply.github.com&gt;;
抄送:&nbsp;"独来独往"<453354858@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [lisen87/image_pickers] 为什么我用华为可以保存到相册 用oppo就不行 (#49)





   
是不是没有找到？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lisen87/image_pickers" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月25日(星期五) 上午9:48 收件人:&nbsp;"lisen87/image_pickers"<image_pickers@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[lisen87/image_pickers] 为什么我用华为可以保存到相册 用oppo就不行 (#49) 为什么我用华为可以保存到相册 用oppo就不行 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
请问没有找到是什么意思？ 我尝试了很多次 确认是相册里没有 但是华为手机可以 是我哪里操作有问题吗 ？ 并且我打包的时候一直报错 Could not resolve com.github.LuckSiege.PictureSelector:picture_library:v2.4.2.
 请问 又是什么情况
  
_saveScreen() async {
 try {
 RenderRepaintBoundary boundary =
 repainKey.currentContext.findRenderObject();
 ui.Image image = await boundary.toImage();
 ByteData byteData =
 await image.toByteData(format: ui.ImageByteFormat.png);
 //这个对象就是图片数据
 Uint8List pngBytes = byteData.buffer.asUint8List();
   String path = await ImagePickers.saveByteDataImageToGallery(pngBytes);   File(path);   ToastUtil.showSuccess('保存成功,请查看相册'); } catch (e) {   ToastUtil.showError('保存失败!'); }  
}
 
这是我的代码

**Comment by lisen87** [comment]
图片保存失败 这样设置试试  boundary.toImage(pixelRatio: 3);





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lisen87/image_pickers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 上午9:56
收件人:&nbsp;"lisen87/image_pickers"<image_pickers@noreply.github.com&gt;;
抄送:&nbsp;"独来独往"<453354858@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [lisen87/image_pickers] 为什么我用华为可以保存到相册 用oppo就不行 (#49)





   
是不是没有找到？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "lisen87/image_pickers" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月25日(星期五) 上午9:48 收件人:&nbsp;"lisen87/image_pickers"<image_pickers@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[lisen87/image_pickers] 为什么我用华为可以保存到相册 用oppo就不行 (#49) 为什么我用华为可以保存到相册 用oppo就不行 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
请问没有找到是什么意思？ 我尝试了很多次 确认是相册里没有 但是华为手机可以 是我哪里操作有问题吗 ？ 并且我打包的时候一直报错 Could not resolve com.github.LuckSiege.PictureSelector:picture_library:v2.4.2.
 请问 又是什么情况
  
_saveScreen() async {
 try {
 RenderRepaintBoundary boundary =
 repainKey.currentContext.findRenderObject();
 ui.Image image = await boundary.toImage();
 ByteData byteData =
 await image.toByteData(format: ui.ImageByteFormat.png);
 //这个对象就是图片数据
 Uint8List pngBytes = byteData.buffer.asUint8List();
   String path = await ImagePickers.saveByteDataImageToGallery(pngBytes);   File(path);   ToastUtil.showSuccess('保存成功,请查看相册'); } catch (e) {   ToastUtil.showError('保存失败!'); }  
}
 
这是我的代码
